# Generated by Django 5.1.2 on 2024-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='dealType',
            field=models.CharField(blank=True, choices=[('0', 'فروش'), ('1', 'خرید'), ('2', 'مزایده')], default=0, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='priceMethod',
            field=models.CharField(blank=True, choices=[('0', 'توافقی'), ('1', 'مشخص')], default=0, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='verification_code',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True),
        ),
    ]
